[server.pv.error]
mod_missing_kick_message = "Üzgünüz, bu sunucuda oynamak için Plasmo Voice modunu yüklemeniz gerekiyor.\nBuradan indirin: https://modrinth.com/plugin/plasmo-voice"
player_not_found = "Öyle bir oyuncu yok"
version_not_supported = "Üzgünüz, Plasmo Voice sürümünüz bu sunucuda desteklenmiyor. %s"
player_only_command = "Bu komutu yalnızca oyuncu çalıştırabilir"
version_not_supported_click = "Desteklenen sürümü indirin"
no_permissions = "Üzgünüm, ancak bu komutu gerçekleştirmek için izniniz yok. Bunun hatalı olduğunu düşünüyorsanız lütfen sunucu yöneticileriyle iletişime geçin."
version_not_supported_hover = "%s"
[server.pv.mutes]
unmuted = "Susturulman kaldırıldı"
empty_reason = "belirtilmemiş"
permanently_muted = "Kalıcı olarak susturuldun: Sebep: %s"
temporarily_muted = "Sesiniz moderatör tarafından devre dışı bırakıldı: %1$s. Sebep: %2$s"

[server.pv.mutes.durations]
hours = "%s saat boyunca"
seconds = "%s saniye boyunca"
weeks = "%s hafta boyunca"
minutes = "%s dakika boyunca"
days = "%s gün boyunca"
[server.pv.command.mute_list]
expiration_time = "HH:mm:ss"
never_expires = "asla"
expiration_date = "yyyy.MM.dd"
empty = "Susturulmuş oyuncu yok"
entry_muted_by = "%1$s oyuncusu %2$s tarafından susturuldu, kalan süre: %3$s. Sebep: %4$s"
entry = "%1$s, kalan süre: %2$s. Sebep: %3$s"
header = "Susturulan oyuncular:"
expire_at = "%1$s, %2$s tarihinde"
[server.pv.command.mute]
already_muted = "%s zaten susturulmuş"
usage = "Kullanım: /vmute <oyuncu> [süre] [sebep]"
permanently_muted = "%1$s kalıcı olarak susturuldu. Sebep: %2$s"
temporarily_muted = "%1$s %2$s susturuldu. Sebep: %3$s"
[server.pv.command.list]
message = "Clients (%1$s/%2$s): %3$s"
empty = "Plasmo Voice kullanan bir oyuncu yok"
[server.pv.command.reconnect]
message = "Yeniden bağlanma paketi gönderildi"
[server.pv.command.reload]
message = "Konfigürasyon yeniden yüklendi"
[server.pv.command.unmute]
unmuted = "%s susturulması kaldırıldı"
usage = "Kullanım: vunmute <oyuncu>"
not_muted = "%s susturulmamış"
[client.pv.activation]
proximity = "Yakınlık"
