[Supercharges]
	#Duration of the supercharge buff in minutes
	# Default: 5
	# Range: 1 ~ 3600
	supercharge_minutes = 5
	#Supercharge Multipliers - Increases in percentage:
	#Dig speed increase:
	# Default: 20
	# Range: 0 ~ 1000
	supercharge_dig_speed = 20
	#Attack speed increase:
	# Default: 20
	# Range: 0 ~ 1000
	supercharge_attack_speed = 20
	#Attack damage increase:
	# Default: 20
	# Range: 0 ~ 1000
	supercharge_attack_damage = 20
	#Supercharge tool unbreakablity:
	supercharge_unbreakable = true

["Paranoia Altar"]
	#Allows players in creative mode to be effected by the Paranoia Altar
	paranoia_altar_effects_creative = false
	# Default: 72
	# Range: 0 ~ 128
	paranoia_altar_horizontal_range = 72
	# Default: 8
	# Range: 0 ~ 128
	paranoia_altar_vertical_range = 8
