debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
type = "VOICE"
toggle = false

[[key_bindings]]
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 93
type = "KEYSYM"

[servers.85b03c1c-b9b4-4874-94f3-2bce08fd972b.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32

[voice]
disabled = false
microphone_disabled = false
activation_threshold = -53.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 2.0
noise_suppression = true
volume = 1.2
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.proximity]
volume = 1.0
[voice.volumes.source_73b3d1c9-5466-3b83-ac37-f3d464fd06d9]
volume = 1.05

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
source_types_overlap = "MUTE_PROXIMITY"
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true
jitter_packet_delay = 3
al_playback_buffers = 5
adaptive_jitter_buffer = false

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "OFF"
